[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CTBN-Voltage-Gated"
version = "0.1.0"
authors = [
  { name="Hannah Wimpy", email="Hannah_Wimpy@hms.harvard.edu" },
]
description = "A GUI application for simulating sodium channel models, implemented as a proof-of-principle. This code accompanies the paper 'Efficient fully stochastic modelling of voltage-gated ion channels using Bayesian networks by Hannah G. Wimpy' and showcases CTBN's advantages over Legacy Hodgkin-Huxley and Markov models for sodium channels." 
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = ["ion channel", "electrophysiology", "simulation", "gui", "computational biology", "neuroscience", "Bayesian networks", "CTBN", "voltage-gated channels", "Hodgkin-Huxley", "Markov model"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta", 
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "numpy>=1.20.0",
    "scipy>=1.7.0",
    "dearpygui>=1.0.0",
    "matplotlib>=3.4.0",
    "pyobjc>=8.0; sys_platform == 'darwin'",
]

[project.urls]
"Homepage" = "https://github.com/hannahgwimpy/CTBN-Voltage-Gated"
"Bug Tracker" = "https://github.com/hannahgwimpy/CTBN-Voltage-Gated/issues" 

[project.scripts]
CTBN-Voltage-Gated = "main:main"

[tool.setuptools.packages.find]
where = ["src"]
